### ISSUE TITLE
Improved meta-model/model visualization

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#221]
Here are some ideas for better visualization. Some of the work is already on `better-dot-visualization` branch:
- [x] Remove base types (there will always be a diagram in the docs for reference)
- [x] Condense match rules in dot visualization -- make a table with match rule names in one column and the match body in the other. This will make large meta-models more readable.
- [ ] Implement model visualization in plantUML using object diagram notation (extend renderers to support model rendering also).
- [x] Change attributes rendering in PlantUML visualization to be `prop_name: prop_type` adhering to UML spec and aligning with dot rendering.
- [ ] Cleanup `export` module

@goto40 I'll work on it in the next days/weeks. Just dumping here some ideas/directions.
